file = require("src.file")

file.sourceFile("plugin/config/ayu-vim")
file.sourceFile("plugin/config/nvim-tree")
file.sourceFile("plugin/config/lualine")
file.sourceFile("plugin/config/treesitter")
file.sourceFile("plugin/config/telescope")
file.sourceFile("plugin/config/floaterm")
file.sourceFile("plugin/config/twilight")
file.sourceFile("plugin/config/ccc")
file.sourceFile("plugin/config/lsp-zero")
file.sourceFile("plugin/config/gitsigns")
file.sourceFile("plugin/config/copilot")
file.sourceFile("plugin/config/autotag")

